import Head from 'next/head'
import { useState,useEffect } from 'react';
import setAuthToken from './utils/jwt';
import jwtDecode from 'jwt-decode';
import { useRouter } from 'next/router';
import Navbar from './components/Navbar';
import Footer from './components/Footer';
export default function Home() {
  const [hasMounted, setHasMounted] = useState(false);
const router=useRouter()
useEffect(() => {
  setHasMounted(true);
  
}, []);
let logUser;
  if (hasMounted){
    if (localStorage.token) {
      const jwt = localStorage.getItem("token");
      setAuthToken(jwt);
      logUser = jwtDecode(jwt);
  }
    
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@700&display=swap" rel="stylesheet"/>
   <link href='https://fonts.googleapis.com/css?family=Baloo+Paaji
' rel="stylesheet"/>
      </Head>
  
          <Navbar/>
          
          <img  className='m' src='../back1.png'/>
         

          
      
      <main>
        <div style={{display:'flex',flexDirection:'column',paddingTop:100}}>
        <button onClick={()=>router.push('#section')} className='detail-line'>
          <span className='detail'>Узнать подробности</span>
          <img className='arrow' src='./arrow.png'/>
          </button>

        

 <div style={{display:'flex',justifyContent:'center', paddingTop:24}}>
 <div id ="section" className='cards'>
          <div className='card-sec'>
          <img  className='icon' src="./free.png"/>
          <span>Сервис доступен бесплатно</span>
          </div>
          </div>
          <div id ="section" className='cards'>
          <div className='card-sec'>

          <img  className='icon' src="./hour.png"/>
          <span>Круглосуточная сдача</span>

          </div>
          </div>
          <div id ="section" className='cards'>
          <div className='card-sec'>

          <img className='icon' src="./rest.png"/>
          <span>Комфортные условия</span>

          </div>
          </div>
          <div id ="section" className='cards'>
          <div className='card-sec'>

          <img  className='icon' src="./quiz.png"/>
          <span>Онлайн тесты и сдача отчетов</span>

          </div>
        </div>

 </div>
       
        

      
       
         
        
        <div style={{display:'flex',justifyContent:'center', paddingTop:24}}> 
        <img src='./circ.png'/>

        </div>
        <div className='home-main'>
          <div className='home'>
            <img src="./question.png"/>
            <span> <b>О чем сайт?</b><br/>AlgoMath - цифрофизированный методический комплекс по дискретной математике, алшоритмам и структурам данных, преподавателем которого является Глущенко Татьяна Александровна  </span>
        </div>
        <div  className='home'>
            <img src="./techer.png"/>
            <span><b>Цель проподвателя?</b><br/>Обеспечение удобства проверки отчетов и домашних заданий. а также их оценка, и связь со студентами</span>

        </div>
        
        <div  className='home'>
            <img src='./student.png'/>
            <span><b>Польза студентам? </b><br/>Комфортная онлайн отправка заданий и отчетов на проверку </span>

        </div>
        
        



        </div>
   
        
        </div>
      
      </main>
      <Footer/>
      
    </>
  )}
  else {
    return null
  }
}
